config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'top#index'
  get 'edit/user'
  #get 'list/new'
  #post 'list/create'
  resources :list, only: %i(new create edit update destroy)
  resources :user, only: %i(edit update)
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user
  validates :title, length: {in: 1..255}
end

app/models/user.rb
class User < ApplicationRecord
  has_many :lists, dependent: :destroy
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  validates :name, presence: true, length: {maximum: 20}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  protected
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/list_controller.rb
class ListController < ApplicationController
  
  before_action :set_list, only: %i(edit update destroy)
  
  def new
    @list = List.new
  end
  
  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to :root
    else
      render action: :new
    end
  end
  
  def edit
  end
  
  def update
    if @list.update_attributes(list_params)
      redirect_to :root
    else
      render action: :edit
    end
  end
  
  def destroy
    @list.destroy
    redirect_to :root
  end
  
  private
    def list_params
      params.require(:list).permit(:title).merge(user: current_user)
    end
    
    def set_list
      @list = List.find_by(id: params[:id])
    end
  
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  
  def index
    @lists = List.where(user: current_user).order("created_at ASC")
  end
  
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  
  def edit
    @user = User.find_by(id: params[:id])
  end
  
  def update
    @user = User.find_by(id: params[:id])
    if @user.update_attributes(user_params)
      redirect_to :root
    else
      render action: edit
    end
  end
  
  private
    def user_params
      params.require(:user).permit(:name)
    end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/list_helper.rb
module ListHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todolist</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'partial/header' if current_user %>
    
    <% if flash[:notice] %>
      <div class="alert alert-info">
        <%= flash[:notice] %>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="alert alert-danger">
        <%= flash[:alert] %>
      </div>
    <% end %>
    
    <%= yield %>
  </body>
</html>

app/views/list/edit.html.erb
<div class="listeditPage">
  <div class="container">
    <%= form_with model: @list, url: { action: :update }, html: { class: 'listForm' }, local: true do |f| %>
      <% if @list.errors.any? %>
        <p class="text-danger">タイトルは1～255文字以内で入力してください</p>
      <% end %>
      <%= f.label :title %>
      <%= f.text_field :title, class: "form-control listName", placeholder: "リスト名" %>
      <div class="text-center"><%= f.submit "編集する", class: "submitBtn" %></div>
    <% end %>
  </div>
</div>

app/views/list/new.html.erb
<div class="listnewPage">
  <div class="container">
    <%= form_with model: @list, url: { action: :create }, class: "new_list", local: true do |f| %>
      <% if @list.errors.any? %>
        <p class="text-danger">タイトルは1～255文字以内で入力してください</p>
      <% end %>
      <%= f.label :title %>
      <%= f.text_field :title, autofocus: true, class: "form-control listName", placeholder: "リスト名" %>
      <div class="text-center"><%= f.submit "作成", class: "submitBtn" %></div>
    <% end %>
  </div>
</div>

app/views/partial/_header.html.erb
<header class="header">
  <nav class="nav">
    <ul class="header_menu">
      <li class="nav-link"><%= link_to current_user.name, edit_user_registration_path %>さん</li>
      <li class="header_menu_title"><%= link_to "ToDoList", root_path, class: "nav-link" %></li>
      <li>
        <ul class="header_menu_inner">
          <li><%= link_to "リストを作成", new_list_path, class: "nav-link listNew" %></li>
          <li><%= link_to "サインアウト", destroy_user_session_path, class: "nav-link", method: :delete %></li>
        </ul>
      </li>
    </ul>
  </nav>
</header>

app/views/top/index.html.erb
<div class="topPage">
  <div class="listWrapper">
    <% @lists.each do |list| %>
      <div class="list">
        <div class="list_header">
          <h2 class="list_header_title"><%= list.title %></h2>
          <div class="list_header_action">
            
            <%= link_to content_tag(:i, '', class: 'fas fa-trash'), list, method: :delete, data: { confirm: "#{list.title}を削除して大丈夫ですか？" } %>
            <%= link_to(content_tag(:i, '', class: 'fas fa-pen'), edit_list_path(list)) %>
            
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/user/edit.html.erb
<div class="listeditPage">
  <div class="container">
    <%= form_with model: @user, url: { action: :update }, html: { class: 'listForm' }, local: true do |f| %>
      <% if @user.errors.any? %>
        <p class="text-danger">名前は20文字以内で入力してください</p>
      <% end %>
      <%= f.label :title %>
      <%= f.text_field :title, class: "form-control listName", placeholder: "名前" %>
      <div class="text-center"><%= f.submit "編集する", class: "submitBtn" %></div>
    <% end %>
  </div>
</div>